import csv
import os

from django.contrib.gis.geos import Point
from django.core.management.base import BaseCommand

from locations.models import CampusLocation

# Map CSV category values → model CATEGORY_CHOICES keys
CATEGORY_MAP = {
    'academics': 'academic',
    'dining': 'cafeteria',
    'dormitory': 'dormitory',
    'teaching blocks': 'classroom',
}


class Command(BaseCommand):
    help = 'Import campus buildings from /data/buildings.csv into CampusLocation'

    def add_arguments(self, parser):
        parser.add_argument(
            '--file',
            type=str,
            default='/data/buildings.csv',
            help='Absolute path to the buildings CSV file (default: /data/buildings.csv)',
        )

    def handle(self, *args, **options):
        csv_path = options['file']

        if not os.path.exists(csv_path):
            self.stderr.write(self.style.ERROR(f'File not found: {csv_path}'))
            return

        imported = 0
        skipped = 0

        with open(csv_path, newline='', encoding='utf-8') as fh:
            reader = csv.DictReader(fh)

            for row in reader:
                name = row.get('name', '').strip()
                if not name:
                    continue

                lat_raw = row.get('latitude', '').strip()
                lon_raw = row.get('longitude', '').strip()

                # ── Coordinate validation ──────────────────────────────────
                if not lat_raw or not lon_raw:
                    self.stdout.write(
                        self.style.WARNING(f'[SKIP] Row {name} has no coordinates.')
                    )
                    skipped += 1
                    continue

                try:
                    lat = float(lat_raw)
                    lon = float(lon_raw)
                except ValueError:
                    self.stdout.write(
                        self.style.WARNING(f'[SKIP] Row {name} has no coordinates.')
                    )
                    skipped += 1
                    continue

                # ── Category mapping ───────────────────────────────────────
                csv_category = row.get('category', '').strip().lower()
                category = CATEGORY_MAP.get(csv_category, 'facility')

                description = row.get('description', '').strip()

                # Point(longitude, latitude) — X=lon, Y=lat for SRID 4326
                point = Point(lon, lat, srid=4326)

                # ── Persist ────────────────────────────────────────────────
                # slug is auto-generated by CampusLocation.save() when blank
                CampusLocation.objects.update_or_create(
                    name=name,
                    defaults={
                        'category': category,
                        'description': description,
                        'point': point,
                        'is_active': True,
                    },
                )
                imported += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Import complete: {imported} location(s) imported, {skipped} skipped.'
            )
        )
