# Generated by Django 4.2.30 on 2026-04-13 11:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('office', 'Office'), ('lab', 'Lab'), ('library', 'Library'), ('dormitory', 'Dormitory'), ('cafeteria', 'Cafeteria'), ('gate', 'Gate'), ('facility', 'Facility')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
