# Generated by Django 4.2.30 on 2026-04-13 11:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('office', 'Office'), ('lab', 'Lab'), ('library', 'Library'), ('dormitory', 'Dormitory'), ('cafeteria', 'Cafeteria'), ('gate', 'Gate'), ('facility', 'Facility')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('is_active', models.BooleanField(default=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(help_text='Main coordinate for the building', srid=4326)),
                ('entrance_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The exact navigation entry point', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='locations_c_slug_0f0b6c_idx'), models.Index(fields=['category'], name='locations_c_categor_2dc73b_idx'), models.Index(fields=['is_active'], name='locations_c_is_acti_2b2771_idx')],
            },
        ),
    ]
