# Generated by Django 4.2.30 on 2026-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuslocation',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('classroom', 'Classroom'), ('office', 'Office'), ('lab', 'Lab'), ('library', 'Library'), ('dormitory', 'Dormitory'), ('cafeteria', 'Cafeteria'), ('gate', 'Gate'), ('facility', 'Facility')], max_length=20),
        ),
    ]
