# Generated by Django 4.2.30 on 2026-04-13 11:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('path_line', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('distance_in_meters', models.FloatField()),
                ('is_accessible', models.BooleanField(default=True, help_text='Whether this path is navigable by wheelchair or similar mobility aid')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_ending_at', to='locations.campuslocation')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_starting_at', to='locations.campuslocation')),
            ],
        ),
    ]
