# Generated by Django 4.2.30 on 2026-04-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_classroom_category'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuspath',
            name='end_node_id',
            field=models.IntegerField(blank=True, help_text='Topology graph node ID for the end endpoint', null=True),
        ),
        migrations.AddField(
            model_name='campuspath',
            name='start_node_id',
            field=models.IntegerField(blank=True, help_text='Topology graph node ID for the start endpoint', null=True),
        ),
        migrations.AlterField(
            model_name='campuspath',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_ending_at', to='locations.campuslocation'),
        ),
        migrations.AlterField(
            model_name='campuspath',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_starting_at', to='locations.campuslocation'),
        ),
    ]
